CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(220) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `puesto` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telefono` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `correo` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `folio` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `loginTime` datetime DEFAULT NULL,
  `photo` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `photo_data` longblob,
  `photo_mime` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `foto_registrada_en` datetime DEFAULT NULL,
  `foto_estatus` enum('PENDIENTE','APROBADA','RECHAZADA') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `foto_revisada_en` datetime DEFAULT NULL,
  `foto_revisada_por` bigint unsigned DEFAULT NULL,
  `foto_motivo_rechazo` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `exam` decimal(5,2) NOT NULL DEFAULT '0.00',
  `intentos` int NOT NULL DEFAULT '0',
  `aprobado` tinyint(1) NOT NULL DEFAULT '0',
  `fecha` datetime DEFAULT NULL,
  `qr` longtext COLLATE utf8mb4_unicode_ci,
  `video` decimal(5,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_folio` (`folio`),
  KEY `fk_users_foto_revisor` (`foto_revisada_por`),
  CONSTRAINT `fk_users_foto_revisor` FOREIGN KEY (`foto_revisada_por`) REFERENCES `admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
